In [1]:
import fpl
import fbref
from datetime import datetime
import pandas as pd
import requests
import json
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
#url 
# Make sure to keep the trailing “/” in the url!
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
response = fpl.get(url)

In [2]:
goalies,defenders,midfielders,attackers = fpl.team_stats(response)

midfielders_stats = fpl.midfielders_stats(response,midfielders)
attackers_stats = fpl.attackers_stats(response,attackers)
defenders_stats = fpl.defenders_stats(response,defenders)
goalies_stats = fpl.goalies_stats(response,goalies)

In [3]:
overall_goalies,overall_defenders,overall_midfielders,overall_attackers = fpl.overall_player_stats(response)

overall_midfielders_stats = fpl.midfielders_stats(response,overall_midfielders)
overall_attackers_stats = fpl.attackers_stats(response,overall_attackers)
overall_defenders_stats = fpl.defenders_stats(response,overall_defenders)
overall_goalies_stats = fpl.goalies_stats(response,overall_goalies)

In [8]:
overall_midfielders_stats = overall_midfielders_stats.assign(f = overall_midfielders_stats["total_points"]+overall_midfielders_stats["xPoints"]+overall_midfielders_stats["total_points_Home/Away"]+overall_midfielders_stats["xPoints_Home/Away"]).sort_values('f',ascending=False).drop('f', axis=1)
overall_midfielders_stats.head(20)

,first_name,second_name,id,minutes,xG,xA,xGC,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,goal_scored,assists,clean_sheets,goals_conceded,bonus,form,diff,team_against,Home/Away
52,Kevin,De Bruyne,301,384,1.59,1.79,1.71,52,35.61,45,33.04,3,5,3,2,9,12.2,220,West Ham,Home
42,Mohamed,Salah,283,375,3.30,0.72,4.43,29,27.96,52,41.16,4,0,0,6,2,5.8,120,Fulham,Home
41,Mohamed,Salah,283,375,3.30,0.72,4.43,29,27.96,52,41.16,4,0,0,6,2,5.8,0,Spurs,Home
95,Kevin,De Bruyne,301,384,1.59,1.79,1.71,52,35.61,30,25.33,3,5,3,2,9,12.2,265,Fulham,Away
59,Marcus,Rashford,335,440,1.98,0.30,8.60,33,25.17,42,29.34,2,2,3,4,4,6.0,55,Aston Villa,Home
3,Gabriel,Martinelli Silva,19,407,0.89,1.98,9.76,33,23.61,39,28.61,2,3,0,11,5,6.6,25,Chelsea,Home
53,Riyad,Mahrez,303,379,1.75,0.46,4.32,22,22.36,42,32.58,1,2,0,4,2,2.2,220,West Ham,Home
69,Joelinton Cássio,Apolinário de Lira,371,439,3.07,0.13,6.75,43,33.27,19,18.70,4,2,0,6,8,7.3,140,Southampton,Home
97,Jack,Grealish,305,427,1.04,1.35,1.93,35,26.32,31,20.65,2,3,2,3,5,8.0,265,Fulham,Away
54,Jack,Grealish,305,427,1.04,1.35,1.93,35,26.32,28,22.60,2,3,2,3,5,8.0,220,West Ham,Home
102,Marcus,Rashford,335,440,1.98,0.30,8.60,33,25.17,31,20.79,2,2,3,4,4,6.0,50,Brighton,Away
2,Bukayo,Saka,13,379,1.41,0.88,9.53,17,18.18,46,27.50,1,1,0,11,3,3.4,25,Chelsea,Home
21,Kaoru,Mitoma,124,450,1.50,0.73,7.33,20,21.26,39,25.85,1,1,1,9,1,4.0,-50,Man Utd,Home
20,Kaoru,Mitoma,124,450,1.50,0.73,7.33,20,21.26,39,25.85,1,1,1,9,1,4.0,80,Wolves,Home
50,Cody,Gakpo,680,387,1.32,0.48,6.27,25,20.27,28,24.12,2,1,0,9,3,4.3,120,Fulham,Home
49,Cody,Gakpo,680,387,1.32,0.48,6.27,25,20.27,28,24.12,2,1,0,9,3,4.3,0,Spurs,Home
124,Lucas,Tolentino Coelho de Lima,603,429,0.68,0.31,9.05,26,16.16,30,24.82,2,1,2,9,1,4.3,45,Crystal Palace,Away
125,Lucas,Tolentino Coelho de Lima,603,429,0.68,0.31,9.05,26,16.16,30,24.82,2,1,2,9,1,4.3,-220,Man City,Away
17,Alexis,Mac Allister,116,432,1.97,1.09,7.26,15,22.69,28,30.77,1,0,1,9,0,3.0,-50,Man Utd,Home
16,Alexis,Mac Allister,116,432,1.97,1.09,7.26,15,22.69,28,30.77,1,0,1,9,0,3.0,80,Wolves,Home

In [10]:
overall_attackers_stats = overall_attackers_stats.assign(f = overall_attackers_stats["total_points"]+overall_attackers_stats["xPoints"]+overall_attackers_stats["total_points_Home/Away"]+overall_attackers_stats["xPoints_Home/Away"]).sort_values('f',ascending=False).drop('f', axis=1)
overall_attackers_stats.head(20)

,first_name,second_name,id,minutes,xG,xA,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,goal_scored,assists,bonus,form,diff,team_against,Home/Away
18,Erling,Haaland,318,383,5.30,0.27,48,36.01,51,32.24,6,3,8,9.5,220,West Ham,Home
28,Erling,Haaland,318,383,5.30,0.27,48,36.01,36,28.91,6,3,8,9.5,265,Fulham,Away
24,Ollie,Watkins,40,450,2.76,0.32,36,29.00,33,32.62,4,1,8,7.3,-55,Man Utd,Away
1,Gabriel,Fernando de Jesus,28,374,4.99,0.15,30,33.41,29,29.39,4,0,6,6.0,25,Chelsea,Home
35,Harry,Kane,427,450,2.78,0.81,35,30.55,23,22.77,3,2,8,7.0,0,Liverpool,Away
23,Alexander,Isak,594,346,1.33,0.36,28,17.40,33,28.38,4,0,4,4.8,140,Southampton,Home
15,Diogo,Teixeira da Silva,288,369,2.71,0.56,34,26.52,21,20.43,4,1,6,6.5,120,Fulham,Home
14,Diogo,Teixeira da Silva,288,369,2.71,0.56,34,26.52,21,20.43,4,1,6,6.5,0,Spurs,Home
3,Ivan,Toney,80,442,3.28,0.44,19,25.44,25,31.09,2,0,3,4.7,15,Nott'm Forest,Home
4,Bryan,Mbeumo,95,347,0.90,0.81,26,18.03,28,28.41,1,3,4,4.5,15,Nott'm Forest,Home
0,Eddie,Nketiah,11,450,3.56,0.40,23,27.44,26,22.65,2,1,3,0.6,25,Chelsea,Home
2,Dominic,Solanke,66,447,2.35,0.45,26,23.75,20,25.54,1,3,3,5.8,-55,Leeds,Home
25,Kai,Havertz,145,420,3.80,0.41,23,31.43,16,18.74,2,0,5,1.2,-25,Arsenal,Away
22,Callum,Wilson,356,252,1.99,0.26,36,18.74,19,15.23,5,1,6,7.0,140,Southampton,Home
29,Julián,Álvarez,319,278,2.71,0.32,28,18.80,21,17.10,3,2,3,4.2,265,Fulham,Away
12,Kelechi,Iheanacho,262,317,2.59,0.55,19,21.01,25,19.42,2,0,3,3.0,35,Everton,Home
19,Julián,Álvarez,319,278,2.71,0.32,28,18.80,20,13.48,3,2,3,4.2,220,West Ham,Home
34,Che,Adams,411,325,1.18,0.39,18,15.89,26,19.46,1,1,3,0.2,-140,Newcastle,Away
16,Darwin,Núñez Ribeiro,297,280,1.66,0.49,18,16.11,21,19.56,2,0,2,1.8,0,Spurs,Home
17,Darwin,Núñez Ribeiro,297,280,1.66,0.49,18,16.11,21,19.56,2,0,2,1.8,120,Fulham,Home

In [14]:
overall_defenders_stats = overall_defenders_stats.assign(f = overall_defenders_stats["total_points"]+overall_defenders_stats["xPoints"]+overall_defenders_stats["total_points_Home/Away"]+overall_defenders_stats["xPoints_Home/Away"]).sort_values('f',ascending=False).drop('f', axis=1)
overall_defenders_stats.head(20)

,first_name,second_name,id,minutes,xG,xA,xGC,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,goal_scored,assists,clean_sheets,goals_conceded,bonus,form,diff,team_against,Home/Away
83,John,Stones,302,368,0.18,0.08,1.41,28,25.68,27,26.30,2,0,1,2,5,4.8,265,Fulham,Away
47,John,Stones,302,368,0.18,0.08,1.41,28,25.68,28,22.49,2,0,1,2,5,4.8,220,West Ham,Home
102,Emerson,Leite de Souza Junior,445,437,0.55,0.31,4.98,44,25.79,17,15.03,2,0,4,3,8,0.0,0,Liverpool,Away
40,Trent,Alexander-Arnold,285,450,0.07,2.46,7.31,24,22.40,29,23.09,0,5,0,10,4,4.0,0,Spurs,Home
41,Trent,Alexander-Arnold,285,450,0.07,2.46,7.31,24,22.40,29,23.09,0,5,0,10,4,4.0,120,Fulham,Home
56,Diogo,Dalot Teixeira,342,450,0.80,0.30,9.77,21,20.46,28,26.48,1,0,2,11,2,4.4,55,Aston Villa,Home
61,Tyrone,Mings,39,450,0.09,0.09,4.12,31,24.33,21,15.53,1,0,3,2,3,6.5,-55,Man Utd,Away
65,Alexandre,Moreno Lopera,694,405,0.18,1.16,3.56,26,26.08,19,17.33,0,1,3,2,2,5.3,-55,Man Utd,Away
2,Benjamin,White,10,450,0.80,0.54,9.97,18,18.30,30,21.21,1,2,0,12,2,3.6,25,Chelsea,Home
44,Konstantinos,Tsimikas,292,308,0.45,0.68,5.67,26,15.90,28,17.22,0,2,3,2,2,1.0,0,Spurs,Home
45,Konstantinos,Tsimikas,292,308,0.45,0.68,5.67,26,15.90,28,17.22,0,2,3,2,2,1.0,120,Fulham,Home
42,Joseph,Gomez,286,450,0.06,0.50,8.13,27,16.74,24,16.48,0,0,4,3,3,1.0,0,Spurs,Home
43,Joseph,Gomez,286,450,0.06,0.50,8.13,27,16.74,24,16.48,0,0,4,3,3,1.0,120,Fulham,Home
58,Lisandro,Martínez,533,427,0.18,0.04,7.90,22,14.68,28,18.11,0,0,3,6,4,3.6,55,Aston Villa,Home
19,Adam,Webster,108,374,0.02,0.05,4.56,19,18.87,22,22.86,0,0,2,4,3,2.4,-50,Man Utd,Home
18,Adam,Webster,108,374,0.02,0.05,4.56,19,18.87,22,22.86,0,0,2,4,3,2.4,80,Wolves,Home
108,Aaron,Cresswell,457,405,0.08,0.68,6.95,22,18.56,24,18.16,0,1,2,4,5,3.7,-220,Man City,Away
107,Aaron,Cresswell,457,405,0.08,0.68,6.95,22,18.56,24,18.16,0,1,2,4,5,3.7,45,Crystal Palace,Away
84,Nathan,Aké,308,429,0.10,0.38,2.44,21,21.62,18,21.80,0,0,3,2,1,1.0,265,Fulham,Away
34,James,Justin,268,447,0.07,0.16,6.11,28,15.34,23,15.54,0,0,4,1,2,0.0,35,Everton,Home

In [18]:
overall_goalies_stats

,first_name,second_name,id,minutes,xGC,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,clean_sheets,goals_conceded,bonus,saves,form,diff,team_against,Home/Away
0,Mark,Travers,72,450,8.43,14,15.68,20,17.04,1,11,1,13,0.0,-55,Leeds,Home
1,Norberto,Murara Neto,574,450,8.33,22,21.24,16,17.67,2,8,2,22,4.0,-55,Leeds,Home
2,David,Raya Martin,81,450,6.16,18,17.14,9,11.03,1,6,4,17,4.0,15,Nott'm Forest,Home
3,Jason,Steele,102,450,7.93,31,19.13,20,12.93,2,8,6,12,4.2,80,Wolves,Home
4,Jason,Steele,102,450,7.93,31,19.13,20,12.93,2,8,6,12,4.2,-50,Man Utd,Home
5,Robert,Sánchez,113,450,4.44,14,15.80,19,16.79,1,5,2,4,0.2,80,Wolves,Home
6,Robert,Sánchez,113,450,4.44,14,15.80,19,16.79,1,5,2,4,0.2,-50,Man Utd,Home
7,Vicente,Guaita,152,450,5.29,19,19.20,28,23.52,1,4,2,13,0.4,-45,West Ham,Home
8,Sam,Johnstone,175,360,3.45,23,19.64,10,8.32,2,3,5,18,4.6,-45,West Ham,Home
9,Bernd,Leno,2,450,6.58,12,13.56,15,14.56,0,6,0,19,2.4,-265,Man City,Home
10,Danny,Ward,254,450,9.06,20,18.44,10,13.44,0,9,3,16,0.0,35,Everton,Home
11,Daniel,Iversen,548,450,7.91,11,13.40,8,9.40,0,8,0,14,2.0,35,Everton,Home
12,Alisson,Ramses Becker,281,450,6.47,14,13.60,23,17.36,1,6,0,11,2.5,0,Spurs,Home
13,Alisson,Ramses Becker,281,450,6.47,14,13.60,23,17.36,1,6,0,11,2.5,120,Fulham,Home
14,Ederson,Santana de Moraes,307,450,3.55,15,21.68,16,21.92,1,4,0,4,2.2,220,West Ham,Home
15,David,De Gea Quintana,327,450,8.14,22,15.42,28,16.70,3,4,0,11,4.4,55,Aston Villa,Home
16,Nick,Pope,376,450,7.06,20,18.12,10,9.28,0,7,3,15,4.3,140,Southampton,Home
17,Emiliano,Martínez Romero,31,405,1.62,24,24.52,27,23.11,3,1,3,9,5.8,-55,Man Utd,Away
18,Kepa,Arrizabalaga,133,450,5.05,18,22.12,18,17.92,1,7,2,15,3.6,-25,Arsenal,Away
19,Jordan,Pickford,182,450,9.70,15,17.10,13,16.40,1,10,0,18,3.0,-35,Leicester,Away
20,Bernd,Leno,2,450,6.58,12,13.56,20,18.12,0,6,0,19,2.4,-120,Liverpool,Away
21,Ederson,Santana de Moraes,307,450,3.55,15,21.68,13,15.00,1,4,0,4,2.2,265,Fulham,Away
22,David,De Gea Quintana,327,450,8.14,22,15.42,19,17.28,3,4,0,11,4.4,50,Brighton,Away
23,Dean,Henderson,398,450,5.04,21,12.68,22,20.44,3,3,1,2,0.0,-15,Brentford,Away
24,Hugo,Lloris,425,405,6.45,17,15.84,18,14.32,1,10,3,17,1.4,0,Liverpool,Away
25,Fraser,Forster,426,405,7.96,17,15.24,8,13.24,0,8,1,18,0.6,0,Liverpool,Away
26,Lukasz,Fabianski,455,450,9.76,17,14.28,21,16.64,2,9,1,15,4.2,45,Crystal Palace,Away
27,Lukasz,Fabianski,455,450,9.76,17,14.28,21,16.64,2,9,1,15,4.2,-220,Man City,Away
28,José,Malheiro de Sá,478,450,6.66,28,18.00,15,20.12,3,3,4,19,5.6,-80,Brighton,Away

In [13]:
overall_midfielders_stats.to_csv(r"C:\Users\hp\Desktop\FPL\Data\midfielder.csv",index=False, encoding='utf-8')
overall_attackers_stats.to_csv(r"C:\Users\hp\Desktop\FPL\Data\attacker.csv",index=False, encoding='utf-8')
overall_defenders_stats.to_csv(r"C:\Users\hp\Desktop\FPL\Data\defender.csv",index=False, encoding='utf-8')

In [15]:
midfielders_stats

,first_name,second_name,id,minutes,xG,xA,xGC,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,goal_scored,assists,clean_sheets,goals_conceded,bonus,form,diff,team_against,Home/Away
0,Bukayo,Saka,13,379,1.41,0.88,9.53,17,18.18,46,27.50,1,1,0,11,3,3.4,25,Chelsea,Home
1,Solly,March,107,450,1.33,1.70,7.33,25,24.32,22,24.25,0,4,1,9,2,5.0,80,Wolves,Home
2,Solly,March,107,450,1.33,1.70,7.33,25,24.32,22,24.25,0,4,1,9,2,5.0,-50,Man Utd,Home
3,Alexis,Mac Allister,116,432,1.97,1.09,7.26,15,22.69,28,30.77,1,0,1,9,0,3.0,80,Wolves,Home
4,Alexis,Mac Allister,116,432,1.97,1.09,7.26,15,22.69,28,30.77,1,0,1,9,0,3.0,-50,Man Utd,Home
5,Jack,Grealish,305,427,1.04,1.35,1.93,35,26.32,28,22.60,2,3,2,3,5,8.0,220,West Ham,Home
6,Marcus,Rashford,335,440,1.98,0.30,8.60,33,25.17,42,29.34,2,2,3,4,4,6.0,55,Aston Villa,Home
7,Jack,Grealish,305,427,1.04,1.35,1.93,35,26.32,31,20.65,2,3,2,3,5,8.0,265,Fulham,Away
8,Marcus,Rashford,335,440,1.98,0.30,8.60,33,25.17,31,20.79,2,2,3,4,4,6.0,50,Brighton,Away

In [16]:
attackers_stats

,first_name,second_name,id,minutes,xG,xA,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,goal_scored,assists,bonus,form,diff,team_against,Home/Away
0,Erling,Haaland,318,383,5.30,0.27,48,36.01,51,32.24,6,3,8,9.5,220,West Ham,Home
1,Ollie,Watkins,40,450,2.76,0.32,36,29.00,33,32.62,4,1,8,7.3,-55,Man Utd,Away
2,Erling,Haaland,318,383,5.30,0.27,48,36.01,36,28.91,6,3,8,9.5,265,Fulham,Away
3,Harry,Kane,427,450,2.78,0.81,35,30.55,23,22.77,3,2,8,7.0,0,Liverpool,Away

In [17]:
defenders_stats

,first_name,second_name,id,minutes,xG,xA,xGC,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,goal_scored,assists,clean_sheets,goals_conceded,bonus,form,diff,team_against,Home/Away
0,Benjamin,White,10,450,0.80,0.54,9.97,18,18.30,30,21.21,1,2,0,12,2,3.6,25,Chelsea,Home
1,Pervis,Estupiñán,586,424,0.43,0.60,6.41,11,16.66,29,23.23,0,0,1,8,0,2.2,80,Wolves,Home
2,Pervis,Estupiñán,586,424,0.43,0.60,6.41,11,16.66,29,23.23,0,0,1,8,0,2.2,-50,Man Utd,Home
3,Ben,Chilwell,139,369,0.36,0.99,4.49,11,21.49,11,15.22,0,0,1,6,3,2.2,-25,Arsenal,Away

In [19]:
goalies_stats

,first_name,second_name,id,minutes,xGC,total_points,xPoints,total_points_Home/Away,xPoints_Home/Away,clean_sheets,goals_conceded,bonus,saves,form,diff,team_against,Home/Away
0,David,Raya Martin,81,450,6.16,18,17.14,9,11.03,1,6,4,17,4.0,15,Nott'm Forest,Home
1,Kepa,Arrizabalaga,133,450,5.05,18,22.12,18,17.92,1,7,2,15,3.6,-25,Arsenal,Away

In [20]:
midfielders_stats.to_csv(r"C:\Users\hp\Desktop\FPL\Data\my_fpl\midfielder.csv",index=False, encoding='utf-8')
attackers_stats.to_csv(r"C:\Users\hp\Desktop\FPL\Data\my_fpl\attacker.csv",index=False, encoding='utf-8')
defenders_stats.to_csv(r"C:\Users\hp\Desktop\FPL\Data\my_fpl\defender.csv",index=False, encoding='utf-8')